var frutas = ["manzana", "melon", "piña"]
console.log(frutas)
console.log(frutas.length)
console.log(frutas[0])
console.log(frutas[1])
console.log(frutas[2])
frutas.push("uvas")
console.log(frutas)
frutas.pop()
console.log(frutas)
frutas.unshift("fresas")
console.log(frutas)
frutas.shift()
console.log(frutas)
var posicion = frutas.indexOf("melon")
console.log(posicion)