console.log('Valores que son falsos por default')
console.log(`Boolean() = ${Boolean()}`)
console.log(`Boolean(0) = ${Boolean(0)}`)
console.log(`Boolean(null) = ${Boolean(null)}`)
console.log(`Boolean(NaN) = ${Boolean(NaN)}`)
console.log(`Boolean(undefined) = ${Boolean(undefined)}`)
console.log(`Boolean(false) = ${Boolean(false)}`)
console.log(`Boolean('') = ${Boolean('')}`)
console.log()
console.log('Valores que son verdaderos por default')
console.log(`Boolean(1), Boolean(5) = ${Boolean(1)}, ${Boolean(5)}`)
console.log(`Boolean('a'), Boolean(' ') = ${Boolean('a')}, ${Boolean(' ')}`)
console.log(`Boolean([]) = ${Boolean([])}`)
console.log(`Boolean({}) = ${Boolean({})}`)
console.log(`Boolean(function(){}) = ${Boolean(function(){})}`)
console.log(`Boolean(true) = ${Boolean(true)}`)