console.log(`typeof 40: ${typeof 40}`)
console.log(`typeof "Nombre": ${typeof "Nombre"}`)
console.log(`typeof true: ${typeof true}`)
console.log(`typeof null: ${typeof null}`)
console.log(`typeof undefined: ${typeof undefined}`)
console.log(`typeof [1, 2, 3]: ${typeof [1, 2, 3]}`)
console.log(`typeof {}: ${typeof {}}`)